#' Streamlined Scatter Plots with ggplot2
#'
#' This function aims to strike a balance between the quick but often less visually appealing plots
#' generated by R's internal plotting functions, and the highly customizable but verbose syntax
#' often required by ggplot2. It allows for the creation of visually pleasing scatter plots with
#' minimal syntax.
#'
#' @param x A string specifying the variable to plot on the x-axis.
#' @param y A string specifying the variable to plot on the y-axis.
#' @param data The data frame containing the data to plot.
#' @param factor_var A string specifying a dichotomous factor variable for coloring points. Default is NULL.
#' @param col A string specifying the color of the points. Default is "steelblue".
#' @param legend_title A string specifying the title of the legend. Default is NULL.
#' @param x_limit A numeric vector specifying the x-axis limits. Default is NULL.
#'
#' @return A ggplot object, with aesthetic mappings and other graphical parameters pre-configured
#' for ease of use and visual appeal.
#'
#' @examples
#' \dontrun{
#' data(mtcars)
#' gg_scatter("mpg", "wt", data = mtcars, factor_var = "am")
#' }
#'
#' @note
#' This function uses `eval()` and `parse()` on the user-supplied variable names.
#' Be cautious when using this function in an environment where the data or variable names
#' are not trusted.
#'
#' @seealso
#' For more advanced customizations, see the ggplot2 package documentation.
#'
#' @export
gg_scatter <- function(x,
                       y,
                       data,
                       factor_var = NULL,
                       col = "steelblue",
                       legend_title = NULL,
                       x_limit = NULL) {

  # Strings zu Code umwandeln, später mit eval() ausführen.
  x <- parse(text = x)
  y <- parse(text = y)

  # ggplot-Objekt
  gg <- ggplot(data = data, aes(x = eval(x), y = eval(y)))

  # Punkte einfärben basierend auf der dichotomen Faktor-Variable
  if (!is.null(factor_var)) {
    factor_var <- parse(text = factor_var)
    gg <- gg + geom_point(aes(color = eval(factor_var)))
  } else {
    gg <- gg + geom_point(color = col)
  }

  # Optional: Begrenzung der x-Achse
  if (!is.null(x_limit)) {
    gg <- gg + coord_cartesian(xlim = x_limit)
  }

  gg <- gg + theme_minimal() +
    labs(x = x, y = y) +
    guides(color = guide_legend(title = legend_title))

  return(gg)
}
