#' Create Histograms with Simplified ggplot2 Syntax
#'
#' This function aims to offer a middle ground between the verbose syntax of ggplot2 and
#' the quick but less visually pleasing plots generated by R's internal plotting functions.
#' It allows for the creation of visually appealing histograms with minimal input.
#'
#' @param data The data frame containing the variable to plot.
#' @param var A string specifying the variable for the histogram.
#' @param title A string specifying the title of the plot. Default is 'Histogram'.
#' @param x_lim A numeric vector specifying the x-axis limits. Default is c(-50, 200).
#' @param x_label A string specifying the label for the x-axis. Default is NULL.
#' @param y_label A string specifying the label for the y-axis. Default is NULL.
#' @param bins An integer specifying the number of bins in the histogram. Default is 30.
#'
#' @return A ggplot object, with aesthetic mappings and other graphical parameters pre-configured
#' for ease of use and visual appeal.
#'
#' @examples
#' \dontrun{
#' data(mtcars)
#' gg_histogram(mtcars, var = "mpg")
#' }
#'
#' @note
#' This function uses `aes_string()`, which internally evaluates the string provided.
#' Be cautious when using this function in an environment where the data or variable names
#' are not trusted.
#'
#' @seealso
#' For more advanced customizations, refer to the ggplot2 package documentation.
#'
#' @export
gg_histogram <- function(data,
                         var,
                         title = 'Histogram',
                         x_lim = c(-50, 200),
                         x_label = NULL,
                         y_label = NULL,
                         bins = 30){

  p <- ggplot(data, aes_string(x = var)) +
    geom_histogram(fill = "steelblue", color = "steelblue", alpha = 0.5, bins = bins) +
    theme_minimal() +
    labs(title = title) +
    xlim(x_lim[1], x_lim[2])

  if (!is.null(x_label)) {
    p <- p + xlab(x_label)
  }

  if (!is.null(y_label)) {
    p <- p + ylab(y_label)
  }

  p
}
